class Currency {
  final String code;
  final String name;
  final String flagEmoji;

  Currency({
    required this.code,
    required this.name,
    required this.flagEmoji,
  });
}

final List<Currency> currencies = [
  Currency(code: 'AED', name: 'United Arab Emirates Dirham', flagEmoji: '🇦🇪'),
  Currency(code: 'AFN', name: 'Afghan Afghani', flagEmoji: '🇦🇫'),
  Currency(code: 'ALL', name: 'Albanian Lek', flagEmoji: '🇦🇱'),
  Currency(code: 'AMD', name: 'Armenian Dram', flagEmoji: '🇦🇲'),
  Currency(
      code: 'ANG', name: 'Netherlands Antillean Guilder', flagEmoji: '🇳🇱'),
  Currency(code: 'AOA', name: 'Angolan Kwanza', flagEmoji: '🇦🇴'),
  Currency(code: 'ARS', name: 'Argentine Peso', flagEmoji: '🇦🇷'),
  Currency(code: 'AUD', name: 'Australian Dollar', flagEmoji: '🇦🇺'),
  Currency(code: 'AWG', name: 'Aruban Florin', flagEmoji: '🇦🇼'),
  Currency(code: 'AZN', name: 'Azerbaijani Manat', flagEmoji: '🇦🇿'),
  Currency(
      code: 'BAM',
      name: 'Bosnia and Herzegovina Convertible Mark',
      flagEmoji: '🇧🇦'),
  Currency(code: 'BBD', name: 'Barbadian Dollar', flagEmoji: '🇧🇧'),
  Currency(code: 'BDT', name: 'Bangladeshi Taka', flagEmoji: '🇧🇩'),
  Currency(code: 'BGN', name: 'Bulgarian Lev', flagEmoji: '🇧🇬'),
  Currency(code: 'BHD', name: 'Bahraini Dinar', flagEmoji: '🇧🇭'),
  Currency(code: 'BIF', name: 'Burundian Franc', flagEmoji: '🇧🇮'),
  Currency(code: 'BMD', name: 'Bermudian Dollar', flagEmoji: '🇧🇲'),
  Currency(code: 'BND', name: 'Brunei Dollar', flagEmoji: '🇧🇳'),
  Currency(code: 'BOB', name: 'Bolivian Boliviano', flagEmoji: '🇧🇴'),
  Currency(code: 'BRL', name: 'Brazilian Real', flagEmoji: '🇧🇷'),
  Currency(code: 'BSD', name: 'Bahamian Dollar', flagEmoji: '🇧🇸'),
  Currency(code: 'BTC', name: 'Bitcoin', flagEmoji: '₿'),
  Currency(code: 'BTN', name: 'Bhutanese Ngultrum', flagEmoji: '🇧🇹'),
  Currency(code: 'BWP', name: 'Botswanan Pula', flagEmoji: '🇧🇼'),
  Currency(code: 'BYN', name: 'Belarusian Ruble', flagEmoji: '🇧🇾'),
  Currency(code: 'BZD', name: 'Belize Dollar', flagEmoji: '🇧🇿'),
  Currency(code: 'CAD', name: 'Canadian Dollar', flagEmoji: '🇨🇦'),
  Currency(code: 'CDF', name: 'Congolese Franc', flagEmoji: '🇨🇩'),
  Currency(code: 'CHF', name: 'Swiss Franc', flagEmoji: '🇨🇭'),
  Currency(
      code: 'CLF', name: 'Chilean Unit of Account (UF)', flagEmoji: '🇨🇱'),
  Currency(code: 'CLP', name: 'Chilean Peso', flagEmoji: '🇨🇱'),
  Currency(code: 'CNH', name: 'Chinese Yuan Offshore', flagEmoji: '🇨🇳'),
  Currency(code: 'CNY', name: 'Chinese Yuan', flagEmoji: '🇨🇳'),
  Currency(code: 'COP', name: 'Colombian Peso', flagEmoji: '🇨🇴'),
  Currency(code: 'CRC', name: 'Costa Rican Colón', flagEmoji: '🇨🇷'),
  Currency(code: 'CUC', name: 'Cuban Convertible Peso', flagEmoji: '🇨🇺'),
  Currency(code: 'CUP', name: 'Cuban Peso', flagEmoji: '🇨🇺'),
  Currency(code: 'CVE', name: 'Cape Verdean Escudo', flagEmoji: '🇨🇻'),
  Currency(code: 'CZK', name: 'Czech Koruna', flagEmoji: '🇨🇿'),
  Currency(code: 'DJF', name: 'Djiboutian Franc', flagEmoji: '🇩🇯'),
  Currency(code: 'DKK', name: 'Danish Krone', flagEmoji: '🇩🇰'),
  Currency(code: 'DOP', name: 'Dominican Peso', flagEmoji: '🇩🇴'),
  Currency(code: 'DZD', name: 'Algerian Dinar', flagEmoji: '🇩🇿'),
  Currency(code: 'EGP', name: 'Egyptian Pound', flagEmoji: '🇪🇬'),
  Currency(code: 'ERN', name: 'Eritrean Nakfa', flagEmoji: '🇪🇷'),
  Currency(code: 'ETB', name: 'Ethiopian Birr', flagEmoji: '🇪🇹'),
  Currency(code: 'EUR', name: 'Euro', flagEmoji: '🇪🇺'),
  Currency(code: 'FJD', name: 'Fijian Dollar', flagEmoji: '🇫🇯'),
  Currency(code: 'FKP', name: 'Falkland Islands Pound', flagEmoji: '🇫🇰'),
  Currency(code: 'GBP', name: 'British Pound Sterling', flagEmoji: '🇬🇧'),
  Currency(code: 'GEL', name: 'Georgian Lari', flagEmoji: '🇬🇪'),
  Currency(code: 'GGP', name: 'Guernsey Pound', flagEmoji: '🇬🇬'),
  Currency(code: 'GHS', name: 'Ghanaian Cedi', flagEmoji: '🇬🇭'),
  Currency(code: 'GIP', name: 'Gibraltar Pound', flagEmoji: '🇬🇲'),
  Currency(code: 'GMD', name: 'Gambian Dalasi', flagEmoji: '🇬🇲'),
  Currency(code: 'GNF', name: 'Guinean Franc', flagEmoji: '🇲🇬'),
  Currency(code: 'GTQ', name: 'Guatemalan Quetzal', flagEmoji: '🇵🇪'),
  Currency(code: 'GYD', name: 'Guyanaese Dollar', flagEmoji: '🇬🇾'),
  Currency(code: 'HKD', name: 'Hong Kong Dollar', flagEmoji: '🇭🇰'),
  Currency(code: 'HNL', name: 'Honduran Lempira', flagEmoji: '🇭🇳'),
  Currency(code: 'HRK', name: 'Croatian Kuna', flagEmoji: '🇭🇷'),
  Currency(code: 'HTG', name: 'Haitian Gourde', flagEmoji: '🇭🇹'),
  Currency(code: 'HUF', name: 'Hungarian Forint', flagEmoji: '🇭🇺'),
  Currency(code: 'IDR', name: 'Indonesian Rupiah', flagEmoji: '🇮🇩'),
  Currency(code: 'ILS', name: 'Israeli New Shekel', flagEmoji: '🇮🇱'),
  Currency(code: 'IMP', name: 'Isle of Man Pound', flagEmoji: '🇮🇲'),
  Currency(code: 'INR', name: 'Indian Rupee', flagEmoji: '🇮🇳'),
  Currency(code: 'IQD', name: 'Iraqi Dinar', flagEmoji: '🇮🇶'),
  Currency(code: 'IRR', name: 'Iranian Rial', flagEmoji: '🇮🇷'),
  Currency(code: 'ISK', name: 'Icelandic Króna', flagEmoji: '🇮🇸'),
  Currency(code: 'JEP', name: 'Jersey Pound', flagEmoji: '🇯🇪'),
  Currency(code: 'JMD', name: 'Jamaican Dollar', flagEmoji: '🇯🇲'),
  Currency(code: 'JOD', name: 'Jordanian Dinar', flagEmoji: '🇯🇴'),
  Currency(code: 'JPY', name: 'Japanese Yen', flagEmoji: '🇯🇵'),
  Currency(code: 'KES', name: 'Kenyan Shilling', flagEmoji: '🇰🇪'),
  Currency(code: 'KGS', name: 'Kyrgystani Som', flagEmoji: '🇰🇬'),
  Currency(code: 'KHR', name: 'Cambodian Riel', flagEmoji: '🇰🇭'),
  Currency(code: 'KMF', name: 'Comorian Franc', flagEmoji: '🇰🇲'),
  Currency(code: 'KPW', name: 'North Korean Won', flagEmoji: '🇰🇵'),
  Currency(code: 'KRW', name: 'South Korean Won', flagEmoji: '🇰🇷'),
  Currency(code: 'KWD', name: 'Kuwaiti Dinar', flagEmoji: '🇰🇼'),
  Currency(code: 'KYD', name: 'Cayman Islands Dollar', flagEmoji: '🇰🇾'),
  Currency(code: 'KZT', name: 'Kazakhstani Tenge', flagEmoji: '🇰🇿'),
  Currency(code: 'LAK', name: 'Laotian Kip', flagEmoji: '🇱🇦'),
  Currency(code: 'LBP', name: 'Lebanese Pound', flagEmoji: '🇱🇧'),
  Currency(code: 'LKR', name: 'Sri Lankan Rupee', flagEmoji: '🇱🇰'),
  Currency(code: 'LRD', name: 'Liberian Dollar', flagEmoji: '🇱🇸'),
  Currency(code: 'LSL', name: 'Lesotho Loti', flagEmoji: '🇱🇸'),
  Currency(code: 'LYD', name: 'Libyan Dinar', flagEmoji: '🇱🇾'),
  Currency(code: 'MAD', name: 'Moroccan Dirham', flagEmoji: '🇲🇦'),
  Currency(code: 'MDL', name: 'Moldovan Leu', flagEmoji: '🇲🇩'),
  Currency(code: 'MGA', name: 'Malagasy Ariary', flagEmoji: '🇲🇬'),
  Currency(code: 'MKD', name: 'Macedonian Denar', flagEmoji: '🇲🇰'),
  Currency(code: 'MMK', name: 'Myanma Kyat', flagEmoji: '🇲🇲'),
  Currency(code: 'MNT', name: 'Mongolian Tugrik', flagEmoji: '🇲🇳'),
  Currency(code: 'MOP', name: 'Macanese Pataca', flagEmoji: '🇲🇴'),
  Currency(code: 'MRU', name: 'Mauritanian Ouguiya', flagEmoji: '🇲🇷'),
  Currency(code: 'MUR', name: 'Mauritian Rupee', flagEmoji: '🇲🇺'),
  Currency(code: 'MVR', name: 'Maldivian Rufiyaa', flagEmoji: '🇲🇻'),
  Currency(code: 'MWK', name: 'Malawian Kwacha', flagEmoji: '🇲🇼'),
  Currency(code: 'MXN', name: 'Mexican Peso', flagEmoji: '🇲🇽'),
  Currency(code: 'MYR', name: 'Malaysian Ringgit', flagEmoji: '🇲🇾'),
  Currency(code: 'MZN', name: 'Mozambican Metical', flagEmoji: '🇲🇿'),
  Currency(code: 'NAD', name: 'Namibian Dollar', flagEmoji: '🇳🇦'),
  Currency(code: 'NGN', name: 'Nigerian Naira', flagEmoji: '🇳🇬'),
  Currency(code: 'NIO', name: 'Nicaraguan Córdoba', flagEmoji: '🇳🇮'),
  Currency(code: 'NOK', name: 'Norwegian Krone', flagEmoji: '🇳🇴'),
  Currency(code: 'NPR', name: 'Nepalese Rupee', flagEmoji: '🇳🇵'),
  Currency(code: 'NZD', name: 'New Zealand Dollar', flagEmoji: '🇳🇿'),
  Currency(code: 'OMR', name: 'Omani Rial', flagEmoji: '🇴🇲'),
  Currency(code: 'PAB', name: 'Panamanian Balboa', flagEmoji: '🇵🇦'),
  Currency(code: 'PEN', name: 'Peruvian Nuevo Sol', flagEmoji: '🇵🇪'),
  Currency(code: 'PGK', name: 'Papua New Guinean Kina', flagEmoji: '🇵🇬'),
  Currency(code: 'PHP', name: 'Philippine Peso', flagEmoji: '🇵🇭'),
  Currency(code: 'PKR', name: 'Pakistani Rupee', flagEmoji: '🇵🇰'),
  Currency(code: 'PLN', name: 'Polish Zloty', flagEmoji: '🇵🇱'),
  Currency(code: 'PYG', name: 'Paraguayan Guarani', flagEmoji: '🇵🇾'),
  Currency(code: 'QAR', name: 'Qatari Rial', flagEmoji: '🇶🇦'),
  Currency(code: 'RON', name: 'Romanian Leu', flagEmoji: '🇷🇴'),
  Currency(code: 'RSD', name: 'Serbian Dinar', flagEmoji: '🇷🇸'),
  Currency(code: 'RUB', name: 'Russian Ruble', flagEmoji: '🇷🇺'),
  Currency(code: 'RWF', name: 'Rwandan Franc', flagEmoji: '🇷🇼'),
  Currency(code: 'SAR', name: 'Saudi Riyal', flagEmoji: '🇸🇦'),
  Currency(code: 'SBD', name: 'Solomon Islands Dollar', flagEmoji: '🇸🇧'),
  Currency(code: 'SCR', name: 'Seychellois Rupee', flagEmoji: '🇸🇨'),
  Currency(code: 'SDG', name: 'Sudanese Pound', flagEmoji: '🇸🇩'),
  Currency(code: 'SEK', name: 'Swedish Krona', flagEmoji: '🇸🇪'),
  Currency(code: 'SGD', name: 'Singapore Dollar', flagEmoji: '🇸🇬'),
  Currency(code: 'SHP', name: 'Saint Helena Pound', flagEmoji: '🇸🇭'),
  Currency(code: 'SLL', name: 'Sierra Leonean Leone', flagEmoji: '🇱🇸'),
  Currency(code: 'SOS', name: 'Somali Shilling', flagEmoji: '🇸🇴'),
  Currency(code: 'SRD', name: 'Surinamese Dollar', flagEmoji: '🇸🇷'),
  Currency(code: 'SSP', name: 'South Sudanese Pound', flagEmoji: '🇸🇸'),
  Currency(code: 'STD', name: 'São Tomé and Príncipe Dobra', flagEmoji: '🇸🇹'),
  Currency(code: 'STN', name: 'São Tomé and Príncipe Dobra', flagEmoji: '🇸🇹'),
  Currency(code: 'SVC', name: 'Salvadoran Colón', flagEmoji: '🇸🇻'),
  Currency(code: 'SYP', name: 'Syrian Pound', flagEmoji: '🇸🇾'),
  Currency(code: 'SZL', name: 'Swazi Lilangeni', flagEmoji: '🇸🇿'),
  Currency(code: 'THB', name: 'Thai Baht', flagEmoji: '🇹🇭'),
  Currency(code: 'TJS', name: 'Tajikistani Somoni', flagEmoji: '🇹🇯'),
  Currency(code: 'TMT', name: 'Turkmenistani Manat', flagEmoji: '🇹🇲'),
  Currency(code: 'TND', name: 'Tunisian Dinar', flagEmoji: '🇹🇳'),
  Currency(code: 'TOP', name: 'Tongan Paʻanga', flagEmoji: '🇹🇴'),
  Currency(code: 'TRY', name: 'Turkish Lira', flagEmoji: '🇹🇷'),
  Currency(code: 'TTD', name: 'Trinidad and Tobago Dollar', flagEmoji: '🇹🇹'),
  Currency(code: 'TWD', name: 'New Taiwan Dollar', flagEmoji: '🇹🇼'),
  Currency(code: 'TZS', name: 'Tanzanian Shilling', flagEmoji: '🇹🇿'),
  Currency(code: 'UAH', name: 'Ukrainian Hryvnia', flagEmoji: '🇺🇦'),
  Currency(code: 'UGX', name: 'Ugandan Shilling', flagEmoji: '🇺🇬'),
  Currency(code: 'USD', name: 'United States Dollar', flagEmoji: '🇺🇸'),
  Currency(code: 'UYU', name: 'Uruguayan Peso', flagEmoji: '🇺🇾'),
  Currency(code: 'UZS', name: 'Uzbekistani Som', flagEmoji: '🇺🇿'),
  Currency(code: 'VES', name: 'Venezuelan Bolívar', flagEmoji: '🇻🇪'),
  Currency(code: 'VND', name: 'Vietnamese Dong', flagEmoji: '🇻🇳'),
  Currency(code: 'VUV', name: 'Vanuatu Vatu', flagEmoji: '🇻🇺'),
  Currency(code: 'WST', name: 'Samoan Tala', flagEmoji: '🇼🇸'),
  Currency(code: 'XAF', name: 'Central African CFA Franc', flagEmoji: '🇲🇱'),
  Currency(code: 'XAG', name: 'Silver Ounce', flagEmoji: '🥈'),
  Currency(code: 'XAU', name: 'Gold Ounce', flagEmoji: '🥇'),
  Currency(code: 'XCD', name: 'East Caribbean Dollar', flagEmoji: '🇪🇨'),
  Currency(code: 'XDR', name: 'Special Drawing Rights (IMF)', flagEmoji: '💲'),
  Currency(code: 'XOF', name: 'West African CFA Franc', flagEmoji: '🇨🇮'),
  Currency(code: 'XPD', name: 'Palladium Ounce', flagEmoji: '🥈'),
  Currency(code: 'XPF', name: 'CFP Franc', flagEmoji: '🇵🇫'),
  Currency(code: 'XPT', name: 'Platinum Ounce', flagEmoji: '🏅'),
  Currency(code: 'YER', name: 'Yemeni Rial', flagEmoji: '🇾🇪'),
  Currency(code: 'ZAR', name: 'South African Rand', flagEmoji: '🇿🇦'),
  Currency(code: 'ZMW', name: 'Zambian Kwacha', flagEmoji: '🇿🇲'),
  Currency(code: 'ZWL', name: 'Zimbabwean Dollar', flagEmoji: '🇿🇼'),
];
